travis:
  secure:
    BINSTAR_TOKEN: ka6BjG8Pj9K6sjXFOAk/7Hq98asgagUHxLXOxIGEGdZixxtTDQPv6XbaZZn1fIg+TY+ZeWW6pjylqrseK7bUktowLeNxVREAnI4C2beTxO6qmK0iO8Z+j9YzL75X3BNtN87k3jWcen8QVsAtTnts7ITZ8ccAM+jdhDSNeQId4sRoh6hIYMs4deH0IEYc/n9upfQpVuruNx5JJ9JBfFoF/eP0fTluvtl56w5y4hpxvZrpixTZYAUtj1rGLeAR02oVn1mPnFMJ902tW8Xdh6aoMzBo6595fxXiwkalUDD5B6b75UNhTyt4u2hTJftE3JJ0Av3JZaHaHmCIeuKV/gf2T8Jeq4gVuR0QUi/Kd5l9cNZtqfEApn8pJi0TdIz2WWeqqFWIHRwCxCJf3SWfGVwmAhBwPjFRj8gLWGeZ7pZknTN9DUjG541U43eDh2z4/2zwDCZB1Fu4N/1K05GyTMDzd4XSDmc7vWchHqfcyyNv6KT3Eo/Iui57ZGSIUuuQkL07nXNx7o+4f3rKjRYZe/fJT33krSBdd8OSeloUa1fmZsBMd1qfOy5Hh2JvylbW8Cfudh7rlgnz3eOFM+o1UMtLRmny95Pz70/xVsHKkkcF+9nxcX6Sc2R9ljqxNE5r/aBMVwFEe+FYPAwVsmlPDi8mQJVO3FFa2IwAHjLk3b2XwZA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
